apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "dragonfly-operator.fullname" . }}-leader-election-rolebinding
  labels:
    {{- include "dragonfly-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: rbac
    app.kubernetes.io/instance: leader-election-rolebinding
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/part-of: {{ include "dragonfly-operator.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "dragonfly-operator.fullname" . }}-leader-election-role
subjects:
  - kind: ServiceAccount
    name: {{ include "dragonfly-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
