apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "penpot.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "penpot.labels" . | nindent 4 }}
spec:
  {{- if not .Values.frontend.autoscaling.enabled }}
  replicas: {{ .Values.frontend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "penpot.frontendSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.frontend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "penpot.frontendSelectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "penpot.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.frontend.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-frontend
          securityContext:
            {{- toYaml .Values.frontend.securityContext | nindent 12 }}
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.port }}
              protocol: TCP
          volumeMounts:
            {{- if eq .Values.config.assets.storageBackend "assets-fs" }}
            - mountPath: /opt/data
              name: app-data
            {{- end }}
            - mountPath: /etc/nginx/nginx.conf
              name: "{{ include "penpot.fullname" . }}-frontend-nginx"
              readOnly: true
              subPath: nginx.conf
          env:
            - name: PENPOT_BACKEND_URI
              value: "http://{{ include "penpot.fullname" . }}-backend.{{ .Release.Namespace }}"
            - name: PENPOT_EXPORTER_URI
              value: "http://{{ include "penpot.fullname" . }}-exporter.{{ .Release.Namespace }}"
            - name: PENPOT_FLAGS
              value: "$PENPOT_FLAGS {{ .Values.config.flags }}"
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
      volumes:
        {{- if eq .Values.config.assets.storageBackend "assets-fs" }}
        - name: app-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default ( include "penpot.fullname" . ) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- end }}
        - configMap:
            defaultMode: 420
            name: "{{ include "penpot.fullname" . }}-frontend-nginx"
          name: "{{ include "penpot.fullname" . }}-frontend-nginx"
      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
