apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "penpot.fullname" . }}-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "penpot.labels" . | nindent 4 }}
spec:
  {{- if not .Values.exporter.autoscaling.enabled }}
  replicas: {{ .Values.exporter.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "penpot.exporterSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.exporter.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "penpot.exporterSelectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "penpot.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.exporter.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-exporter
          securityContext:
            {{- toYaml .Values.exporter.securityContext | nindent 12 }}
          image: "{{ .Values.exporter.image.repository }}:{{ .Values.exporter.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.exporter.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.exporter.service.port }}
              protocol: TCP
          env:
            - name: PENPOT_PUBLIC_URI
              value: {{ .Values.config.publicURI }}
            - name: PENPOT_REDIS_URI
              value: redis://{{ .Values.config.redis.host }}:{{ .Values.config.redis.port }}/{{ .Values.config.redis.database }}
          resources:
            {{- toYaml .Values.exporter.resources | nindent 12 }}
      {{- with .Values.exporter.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.exporter.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.exporter.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
