apiVersion: v1
kind: Service
metadata:
  name: {{ include "mixpost.fullname" . }}
  labels:
    {{- include "mixpost.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: "http"
      port: {{ .Values.service.port }}
  selector:
    {{- include "mixpost.selectorLabels" . | nindent 4 }}

